import type { Metadata } from "next";
import { Clock3, Linkedin, Mail, MapPin, Phone, Twitter } from "lucide-react";
import { ContactForm } from "@/components/analytics/contact-form";
import { Breadcrumb } from "@/components/pages/breadcrumb";
import { PageHero } from "@/components/pages/page-hero";
import { Container } from "@/components/ui/container";
import { Heading } from "@/components/ui/heading";
import { Section } from "@/components/ui/section";

export const metadata: Metadata = { title: "Contact", description: "Start a conversation with the Lumora digital marketing agency team." };
const faqs = [["What happens after I send an enquiry?", "We review every message personally and reply within two working days. If there is a strong fit, we will arrange a focused discovery call."], ["What should I include in my message?", "Your goals, current challenge, timing, and a rough budget range are the most useful starting points. There is no need for a formal brief."], ["Do you work with teams outside New York and London?", "Yes. Our team works remotely with ambitious brands across North America, Europe, and beyond."]];

export default function ContactPage() { return <><Breadcrumb current="Contact" /><PageHero eyebrow="CONTACT" title="Let’s create some momentum." description="Tell us about the challenge, opportunity, or ambitious target you cannot stop thinking about." cta="Email us directly" ctaHref="mailto:hello@lumora.example" /><Section className="pt-0"><Container className="grid gap-8 lg:grid-cols-[.82fr_1.18fr]"><ContactDetails /><ContactForm /></Container></Section><Section className="bg-muted/55"><Container className="grid gap-8 lg:grid-cols-[1.1fr_.9fr]"><MapPlaceholder /><BusinessHours /></Container></Section><Section><Container className="max-w-4xl"><div className="text-center"><p className="text-sm font-semibold text-primary">CONTACT FAQ</p><Heading className="mt-3">A few helpful answers.</Heading></div><div className="mt-10 divide-y">{faqs.map(([question, answer]) => <details key={question} className="group py-5"><summary className="cursor-pointer list-none font-semibold marker:hidden">{question}</summary><p className="pt-4 leading-7 text-muted-foreground">{answer}</p></details>)}</div></Container></Section></>; }

function ContactDetails() { return <aside className="rounded-3xl bg-slate-950 p-7 text-white sm:p-8"><p className="text-sm font-semibold text-cyan-300">START A CONVERSATION</p><Heading as="h2" size="card" className="mt-3 text-white">Prefer the direct route?</Heading><p className="mt-4 text-sm leading-6 text-slate-300">Write, call, or connect with our team. We are a small enough agency to make every first conversation count.</p><div className="mt-8 space-y-5 text-sm"><a href="mailto:hello@lumora.example" className="flex items-center gap-3 hover:text-cyan-300"><Mail size={18} className="text-cyan-300" />hello@lumora.example</a><a href="tel:+12125550189" className="flex items-center gap-3 hover:text-cyan-300"><Phone size={18} className="text-cyan-300" />+1 (212) 555-0189</a><p className="flex items-start gap-3"><MapPin size={18} className="mt-0.5 shrink-0 text-cyan-300" />225 Hudson Street, New York, NY 10013</p></div><div className="mt-9 border-t border-white/10 pt-6"><p className="text-xs font-semibold tracking-wider text-slate-400">FOLLOW LUMORA</p><div className="mt-4 flex gap-3"><SocialLink href="https://www.linkedin.com" label="LinkedIn"><Linkedin size={18} /></SocialLink><SocialLink href="https://x.com" label="X"><Twitter size={18} /></SocialLink></div></div></aside>; }
function SocialLink({ href, label, children }: { href: string; label: string; children: React.ReactNode }) { return <a href={href} target="_blank" rel="noreferrer" aria-label={label} className="inline-flex h-10 w-10 items-center justify-center rounded-full border border-white/15 text-slate-200 transition hover:border-cyan-300 hover:text-cyan-300">{children}</a>; }
function MapPlaceholder() { return <div className="relative min-h-80 overflow-hidden rounded-3xl border bg-slate-200 dark:bg-slate-800" role="img" aria-label="Map placeholder showing Lumora's New York office near Hudson Street"><div className="absolute inset-0 opacity-60 [background-image:linear-gradient(30deg,transparent_48%,rgba(37,99,235,.18)_49%,rgba(37,99,235,.18)_51%,transparent_52%),linear-gradient(-40deg,transparent_47%,rgba(124,58,237,.18)_48%,rgba(124,58,237,.18)_50%,transparent_51%)] [background-size:80px_80px]" /><div className="absolute left-1/2 top-1/2 flex -translate-x-1/2 -translate-y-1/2 flex-col items-center"><span className="flex h-14 w-14 items-center justify-center rounded-full bg-primary text-white shadow-lg"><MapPin size={26} /></span><div className="mt-3 rounded-xl bg-surface px-4 py-2 text-sm font-semibold shadow-glass">Lumora, New York</div></div></div>; }
function BusinessHours() { return <div className="rounded-3xl border bg-surface p-7 sm:p-8"><Clock3 className="text-primary" size={25} /><Heading as="h2" size="card" className="mt-6">Business hours</Heading><p className="mt-3 text-sm leading-6 text-muted-foreground">Our team is available across New York and London time zones.</p><dl className="mt-7 divide-y text-sm"><div className="flex justify-between py-3"><dt>Monday–Thursday</dt><dd className="font-semibold">9:00–18:00</dd></div><div className="flex justify-between py-3"><dt>Friday</dt><dd className="font-semibold">9:00–16:00</dd></div><div className="flex justify-between py-3"><dt>Weekend</dt><dd className="font-semibold text-muted-foreground">Closed</dd></div></dl></div>; }
