"use client";

import { ArrowRight, BarChart3, Sparkles } from "lucide-react";
import { motion, useScroll, useTransform } from "framer-motion";
import { useRef } from "react";
import { Button } from "@/components/ui/button";
import { Container } from "@/components/ui/container";
import { Heading } from "@/components/ui/heading";

export function Hero() {
  const sectionRef = useRef<HTMLElement>(null);
  const { scrollYProgress } = useScroll({ target: sectionRef, offset: ["start start", "end start"] });
  const visualY = useTransform(scrollYProgress, [0, 1], [0, 70]);
  const copyY = useTransform(scrollYProgress, [0, 1], [0, 25]);
  return <section ref={sectionRef} className="relative overflow-hidden py-20 sm:py-28 lg:py-36"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_80%_15%,rgba(6,182,212,.16),transparent_22%),radial-gradient(circle_at_20%_35%,rgba(124,58,237,.14),transparent_25%)]" /><Container className="grid items-center gap-14 lg:grid-cols-[1.05fr_.95fr]"><motion.div style={{ y: copyY }} initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .6, ease: [0.22, 1, 0.36, 1] }}><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/15 bg-primary/5 px-3 py-1.5 text-sm font-medium text-primary"><Sparkles size={15} />Growth marketing for ambitious brands</div><Heading as="h1" size="display">Turn attention into <span className="bg-gradient-to-r from-primary via-secondary to-accent bg-clip-text text-transparent">lasting growth.</span></Heading><p className="mt-6 max-w-xl text-lg leading-8 text-muted-foreground">Lumora combines sharp strategy, standout creative, and performance media to make your next stage of growth inevitable.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button href="/contact">Book a growth call <ArrowRight className="ml-2" size={17} /></Button><Button href="/work" variant="outline">Explore our work</Button></div><p className="mt-7 text-sm text-muted-foreground">Trusted by growth teams at category-defining companies.</p></motion.div><motion.div style={{ y: visualY }} initial={{ opacity: 0, scale: .96 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: .7, delay: .12, ease: [0.22, 1, 0.36, 1] }} className="relative mx-auto w-full max-w-lg"><div className="absolute -inset-6 rounded-[2.5rem] bg-gradient-to-br from-primary/20 via-secondary/10 to-accent/20 blur-3xl" /><Dashboard /></motion.div></Container></section>;
}

function Dashboard() { return <div className="glass relative overflow-hidden rounded-[2rem] p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="text-xs font-medium text-muted-foreground">Growth dashboard</p><p className="mt-1 text-2xl font-semibold">$284,610</p></div><div className="rounded-2xl bg-emerald-500/10 px-3 py-2 text-sm font-semibold text-emerald-600">+42.8%</div></div><div className="mt-7 flex h-44 items-end gap-2">{[35,47,42,62,56,74,69,91,82,100].map((height, index) => <motion.div key={index} className="flex-1 rounded-t-md bg-gradient-to-t from-primary to-accent opacity-90" initial={{ height: 0 }} animate={{ height: `${height}%` }} transition={{ duration: .5, delay: .35 + index * .05 }} />)}</div><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-muted p-4"><BarChart3 className="text-primary" size={20} /><p className="mt-5 text-sm text-muted-foreground">Qualified leads</p><p className="mt-1 text-xl font-semibold">3,842</p></div><div className="rounded-2xl bg-muted p-4"><div className="h-5 w-5 rounded-full bg-secondary" /><p className="mt-5 text-sm text-muted-foreground">Conversion rate</p><p className="mt-1 text-xl font-semibold">8.64%</p></div></div></div>; }
